services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: hw2_app
    restart: always
    networks:
      - hw2_networks

  postgres:
    image: postgres:12
    container_name: hw2_postgres
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - hw2_networks

networks:
  hw2_networks:
    driver: bridge

volumes:
  postgres-data:
